# Generated by Django 5.0.3 on 2024-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='group',
        ),
        migrations.AddField(
            model_name='material',
            name='groups',
            field=models.ManyToManyField(related_name='materials', to='auth.group'),
        ),
    ]
